//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IgorMarkivMessengerDBEntities : DbContext
    {
        public IgorMarkivMessengerDBEntities()
            : base("name=IgorMarkivMessengerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<siteVisits> siteVisits { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ErrorLogs> ErrorLogs { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<MessageInfo> MessageInfo { get; set; }
        public virtual DbSet<msg_conv> msg_conv { get; set; }
        public virtual DbSet<InvitationCode> InvitationCode { get; set; }
        public virtual DbSet<userSettings> userSettings { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<thumbnails> thumbnails { get; set; }
        public virtual DbSet<FilesTags> FilesTags { get; set; }
    }
}
