//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int id { get; set; }
        public string name { get; set; }
        public int user { get; set; }
        public Nullable<long> size { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public string md5 { get; set; }
        public string guid { get; set; }
        public string rout { get; set; }
        public string type { get; set; }
    }
}
