//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix.DBHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public long id { get; set; }
        public int user_id { get; set; }
        public System.DateTime start_date { get; set; }
        public int points { get; set; }
        public bool test_game { get; set; }
        public int spent_time { get; set; }
        public System.DateTime game_lifetime { get; set; }
        public bool is_active { get; set; }
        public Nullable<int> active_stage { get; set; }
        public Nullable<System.DateTime> last_stage_generation_datetime { get; set; }
        public string game_session_key { get; set; }
    }
}
