//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageInfo
    {
        public int id { get; set; }
        public int convId { get; set; }
        public int messageBodyId { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<bool> changed { get; set; }
        public bool isUser1 { get; set; }
    
        public virtual message message { get; set; }
        public virtual msg_conv msg_conv { get; set; }
    }
}
