//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helix.DBHelper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stages
    {
        public int Id { get; set; }
        public string question { get; set; }
        public string correctAnswer { get; set; }
        public string incorrectAnswer1 { get; set; }
        public string incorrectAnswer2 { get; set; }
        public string incorrectAnswer3 { get; set; }
        public int level { get; set; }
        public Nullable<long> times_answered { get; set; }
    }
}
